### PR TITLE
Add `getAccountForUfvk`  method to Rust backend & fix key derivation null issue.

### LINKED ISSUE #1651: Incorrect documentation of RustBackend.importAccountUfvk JNI function
Originally posted by @daira in https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1640#discussion_r1881222624 :
> The suggestions to add "Only used if `purpose` is 0 (Spending)." depended on the suggestion [below](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1640/files#r1874197278) to only convert/check these parameters in that case. By taking the comment suggestion but not the code suggestion, this is now incorrectly documented, because `seed_fingerprint_bytes` has to point to a 32-byte array and `hd_account_index_raw` has to be in the range of a valid ZIP 32 account index, *regardless* of `purpose`.

### PR DESCRIPTION
**Pull request by nuttycom**
Fixes #1651 

> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] **Self-review** your own code in GitHub's web interface[^1]
- [ ] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [ ] Update **documentation** as appropriate (e.g [README.md](../blob/main/README.md), [Architecture.md](../blob/main/docs/Architecture.md), etc.)
- [ ] **Run the demo app** and try the changes
- [ ] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

# Reviewer

- [x] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [x] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [ ] Review the **documentation**, [README.md](../blob/main/README.md), [Architecture.md](/blob/main/docs/Architecture.md), etc. as appropriate
- [x] **Run the demo app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you had to manually test 
something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the demo app to look for build failures or crashes, humans running the demo app are 
more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

File: backend-lib/src/main/rust/lib.rs [hunk 1]
```diff
@@ -521,18 +555,23 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_importAcc
...
+                } else {
+                    None
+                };
+                let hd_account_index = zip32::AccountId::try_from(hd_account_index_raw).ok();
+
+                let derivation = seed_fingerprint
+                    .zip(hd_account_index)
+                    .map(|(seed_fp, idx)| Zip32Derivation::new(seed_fp, idx));
+
+                Ok(AccountPurpose::Spending { derivation })
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:573]: I'm confused; `AccountPurpose::Spending` seems to have two arguments both before and after https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1653/commits/e8c1b4a9d59e5c64818559359d188d3c2bbc2f2b .

Comment (nuttycom) [reply backend-lib/src/main/rust/lib.rs:573]: I'm not sure what you're looking at here; the relevant code is https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/data_api.rs#L374-L380

**Review by HonzaR — APPROVED** [review]

**Review by Milan-Cerovsky — APPROVED** [review]
