### PR TITLE
JNI bugfixes

### LINKED ISSUE #1657: Error while inserting UTXO: Network type mismatch
#### If so, please list the steps to reproduce below:
1. 
2. 
3. 

### Actual behavior + errors
```
                 java.lang.RuntimeException: Error while inserting UTXO: Data DB is corrupted: Network type mismatch: account UIVK is for mainnet but a testnet address was requested.
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend.putUtxo(Native Method)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend.access$putUtxo(RustBackend.kt:27)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.putUtxo(Unknown Source:0)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$Companion.access$putUtxo(RustBackend.kt:499)
                 	at cash.z.ecc.android.sdk.internal.jni.RustBackend$putUtxo$2.invokeSuspend(RustBackend.kt:463)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                 	at java.lang.Thread.run(Thread.java:1012)
```

- App Version: 
- Android Version:
- Device: (if applies)

### LINKED ISSUE #1684: RustDerivationTool: Fix inconsistency in `account_index` type across JNI
Currently the JNI uses `Long` on the Kotlin side, but `jint` on the Rust side. Example:
https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/a3ac1d3dda29412977f82e6e3d67383890bd1556/backend-lib/src/main/rust/lib.rs#L2171-L2178
https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/a3ac1d3dda29412977f82e6e3d67383890bd1556/backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustDerivationTool.kt#L68-L71

I thought we'd fixed all of these when we migrated `RustBackend` to the new account APIs. We should check what is going on here and fix as necessary.

### PR DESCRIPTION
**Pull request by str4d**
This fixes multiple JNI type signature inconsistencies, and cleans up argument handling on the Rust side to be less error-prone.

fixes #1657, fixes #1684

> **Note**
>This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] **Self-review** your own code in GitHub's web interface[^1]
- [ ] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [ ] Update **documentation** as appropriate (e.g [README.md](../blob/main/README.md), [Architecture.md](../blob/main/docs/Architecture.md), etc.)
- [ ] **Run the demo app** and try the changes
- [ ] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

# Reviewer

- [ ] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [ ] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [ ] Review the **documentation**, [README.md](../blob/main/README.md), [Architecture.md](/blob/main/docs/Architecture.md), etc. as appropriate
- [ ] **Run the demo app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you had to manually test 
something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the demo app to look for build failures or crashes, humans running the demo app are 
more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

File: backend-lib/src/main/rust/lib.rs [hunk 1]
```diff
@@ -396,7 +396,7 @@ fn encode_usk<'a>(
 }
 
 fn decode_usk(env: &JNIEnv, usk: JByteArray) -> anyhow::Result<UnifiedSpendingKey> {
-    let usk_bytes = SecretVec::new(env.convert_byte_array(usk).unwrap());
+    let usk_bytes = parse_secret(env, &usk)?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:399]: Nit: `parse_secret` should be called `secret_from_jni` (like `account_id_from_jni`), because it isn't doing any parsing.

File: backend-lib/src/main/rust/lib.rs [hunk 2]
```diff
@@ -443,8 +443,8 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createAcc
     let res = catch_unwind(&mut env, |env| {
         let network = parse_network(network_id as u32)?;
         let mut db_data = wallet_db(env, network, db_data)?;
-        let seed = SecretVec::new(env.convert_byte_array(seed).unwrap());
-        let treestate = TreeState::decode(&env.convert_byte_array(treestate).unwrap()[..])
+        let seed = parse_secret(env, &seed)?;
+        let treestate = TreeState::decode(utils::java_bytes_to_rust(env, &treestate)?.as_slice())
             .map_err(|e| anyhow!("Invalid TreeState: {}", e))?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:448]: There are three identical uses of this pattern. Add a `treestate_from_jni` helper.

File: backend-lib/src/main/rust/lib.rs [hunk 3]
```diff
@@ -236,7 +236,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_initDataD
         let mut db_data = wallet_db(env, network, db_data)
             .map_err(|e| anyhow!("Error while opening data DB: {}", e))?;
 
-        let seed = (!seed.is_null()).then(|| SecretVec::new(env.convert_byte_array(seed).unwrap()));
+        let seed = utils::java_nullable_bytes_to_rust(env, &seed)?.map(SecretVec::new);
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:239]: Nit: There are two uses of this pattern. It's marginal, but I would add a nullable counterpart to `parse_secret`.

File: backend-lib/src/main/rust/lib.rs [hunk 4]
```diff
@@ -1809,7 +1802,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_proposeTr
         let network = parse_network(network_id as u32)?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:1794]: On line 1801 the wrong method name is used in the `info_span!`.

File: backend-lib/src/main/rust/lib.rs [hunk 5]
```diff
@@ -1855,21 +1848,19 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_proposeTr
...
-        } else {
-            MemoBytes::from_bytes(&env.convert_byte_array(memo)?)
-                .map(Some)
-                .map_err(|e| anyhow!("Invalid MemoBytes: {}", e))?
-        };
+        let memo = utils::java_nullable_bytes_to_rust(env, &memo)?
+            .as_deref()
+            .map(MemoBytes::from_bytes)
+            .transpose()
+            .map_err(|e| anyhow!("Invalid MemoBytes: {}", e))?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:1855]: This pattern occurs twice (also in `RustBackend.proposeShielding`); consider adding a `nullable_memo_from_jni` helper.

File: backend-lib/src/main/rust/lib.rs [hunk 6]
```diff
@@ -530,15 +530,15 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_importAcc
...
         let mut db_data = wallet_db(env, network, db_data)?;
-        let ufvk_str = java_string_to_rust(env, &ufvk_str);
+        let ufvk_str = java_string_to_rust(env, &ufvk_str)?;
         let ufvk = UnifiedFullViewingKey::decode(&network, &ufvk_str).map_err(|e| {
             anyhow!(
                 "Value \"{}\" did not decode as a valid UFVK: {}",
                 ufvk_str,
                 e
             )
         })?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:540]: There are three near-identical uses of this pattern (one uses `map_err` rather than `match`). Add a `ufvk_from_jni` helper.

File: backend-lib/src/main/rust/lib.rs [hunk 7]
```diff
@@ -552,18 +552,15 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_importAcc
...
-                    <[u8; 32]>::try_from(&env.convert_byte_array(seed_fingerprint_bytes)?[..])
-                        .ok()
-                        .map(SeedFingerprint::from_bytes)
-                } else {
-                    None
-                };
+                let seed_fingerprint =
+                    utils::java_nullable_bytes_to_rust(env, &seed_fingerprint_bytes)?
+                        .and_then(|b| b.as_slice().try_into().ok())
+                        .map(SeedFingerprint::from_bytes);
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:563]: Although this happens to only be used once, it's doing the same kind of thing as the other conversion methods, so I might be inclined to add a helper anyway.

File: backend-lib/src/main/rust/lib.rs [hunk 8]
```diff
@@ -831,7 +828,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_isValidSa
     let res = catch_unwind(&mut env, |env| {
         let _span = tracing::info_span!("RustBackend.isValidSaplingAddress").entered();
         let network = parse_network(network_id as u32)?;
-        let addr = utils::java_string_to_rust(env, &addr);
+        let addr = utils::java_string_to_rust(env, &addr)?;
 
         match Address::decode(&network, &addr) {
             Some(addr) => match addr {
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:834]: Consider this helper:
```rust
fn parse_address(env: &JNIEnv, addr: JString<'local>, network_id: jint) -> anyhow::Result<ZcashAddress> {
    let network = parse_network(network_id as u32)?;
    let addr = utils::java_string_to_rust(env, &addr)?;
    Address::decode(&network, &addr).ok_or(anyhow!("Address is for the wrong network"))
}
```
Then lines 830-839 become just:
```rust
            match parse_address(network_id as u32, &addr)? {
                Address::Sapling(_) => Ok(JNI_TRUE),
                Address::Transparent(_) | Address::Unified(_) | Address::Tex(_) => Ok(JNI_FALSE),
            }
```
This can also be used in `isValid{Transparent,Unified,Tex}Address`, saving 15 non-blank lines overall I think.

File: backend-lib/src/main/rust/lib.rs [hunk 9]
```diff
@@ -2036,12 +2025,12 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createPro
         let network = parse_network(network_id as u32)?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2017]: On line 2024 the wrong method name is used in the `info_span!`.

File: backend-lib/src/main/rust/lib.rs [hunk 10]
```diff
@@ -2169,8 +2157,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_requiresS
     let res = catch_unwind(&mut env, |env| {
         let _span = tracing::info_span!("RustBackend.pcztRequiresSaplingProofs").entered();
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2150]:
```suggestion
        let _span = tracing::info_span!("RustBackend.requiresSaplingProofs").entered();
```

Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2150]: This is the correct name, but the mangled function name is wrong on line 2150. How did this ever work? (I assume it didn't, and so we must have inadequate test coverage.)

File: backend-lib/src/main/rust/lib.rs (hunk 9 above)
Comment (daira) [reply backend-lib/src/main/rust/lib.rs:2017]: I checked all other uses of `info_span!` and made comments for any inconsistencies.

File: backend-lib/src/main/rust/lib.rs [hunk 11]
```diff
@@ -2169,8 +2157,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_requiresS
...
 
-        let pczt = Pczt::parse(&env.convert_byte_array(pczt)?[..])
-            .map_err(|e| anyhow!("Invalid PCZT: {:?}", e))?;
+        let pczt = parse_pczt(env, &pczt)?;
 
         let prover = Prover::new(pczt);
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2155]: Aside (just below): I'm perplexed that there is no `From<bool> for jboolean`. Doesn't matter I guess; this pattern only occurs once.

File: backend-lib/src/main/rust/lib.rs [hunk 12]
```diff
@@ -2540,7 +2526,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_model_TorClient_createTor
     tor_dir: JString<'local>,
 ) -> jlong {
     let res = catch_unwind(&mut env, |env| {
-        let tor_dir = utils::java_string_to_rust(env, &tor_dir);
+        let tor_dir = utils::java_string_to_rust(env, &tor_dir)?;
         let tor_dir = Path::new(&tor_dir);
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2522]: It happens that all of the uses of `Path::new` in this file (7 of them) are from Java strings. So this helper:
```rust
fn path_from_jni(env: &JNIEnv, path_str: &JString) -> anyhow::Result<Path> {
    Ok(Path::new(utils::java_string_to_rust(env, path_str)?))
}
```
would let all paths be immediately typed as `Path` and eliminate all of the `Path::new`s.

File: backend-lib/src/main/rust/lib.rs [hunk 13]
```diff
@@ -2250,14 +2236,14 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_extractAn
...
-        let pczt_with_signatures = Pczt::parse(&env.convert_byte_array(pczt_with_signatures)?[..])
-            .map_err(|e| anyhow!("Invalid PCZT-with-proofs: {:?}", e))?;
+        let pczt_with_signatures = parse_pczt(env, &pczt_with_signatures)
+            .map_err(|e| anyhow!("Invalid PCZT-with-signatures: {:?}", e))?;
 
-        let spend_params = utils::java_string_to_rust(env, &spend_params);
-        let output_params = utils::java_string_to_rust(env, &output_params);
+        let spend_params = utils::java_string_to_rust(env, &spend_params)?;
+        let output_params = utils::java_string_to_rust(env, &output_params)?;
         let prover = LocalTxProver::new(Path::new(&spend_params), Path::new(&output_params));
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2239]:
```suggestion
        let spend_params = path_from_jni(env, &spend_params)?;
        let output_params = path_from_jni(env, &output_params)?;
        let prover = LocalTxProver::new(&spend_params, &output_params);
```

File: backend-lib/src/main/rust/lib.rs [hunk 14]
```diff
@@ -2210,8 +2196,8 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_addProofs
         assert!(!prover.requires_orchard_proof());
 
         if prover.requires_sapling_proofs() {
-            let spend_params = utils::java_string_to_rust(env, &spend_params);
-            let output_params = utils::java_string_to_rust(env, &output_params);
+            let spend_params = utils::java_string_to_rust(env, &spend_params)?;
+            let output_params = utils::java_string_to_rust(env, &output_params)?;
             let local_prover =
                 LocalTxProver::new(Path::new(&spend_params), Path::new(&output_params));
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2194]:
```suggestion
            let spend_params = path_from_jni(env, &spend_params)?;
            let output_params = path_from_jni(env, &output_params)?;
            let prover = LocalTxProver::new(&spend_params, &output_params);
```

File: backend-lib/src/main/rust/lib.rs [hunk 15]
```diff
@@ -2036,12 +2025,12 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createPro
         let network = parse_network(network_id as u32)?;
         let mut db_data = wallet_db(env, network, db_data)?;
         let usk = decode_usk(env, usk)?;
-        let spend_params = utils::java_string_to_rust(env, &spend_params);
-        let output_params = utils::java_string_to_rust(env, &output_params);
+        let spend_params = utils::java_string_to_rust(env, &spend_params)?;
+        let output_params = utils::java_string_to_rust(env, &output_params)?;
 
         let prover = LocalTxProver::new(Path::new(&spend_params), Path::new(&output_params));
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2023]:
```suggestion
        let spend_params = path_from_jni(env, &spend_params)?;
        let output_params = path_from_jni(env, &output_params)?;
        let prover = LocalTxProver::new(&spend_params, &output_params);
```

File: backend-lib/src/main/rust/lib.rs [hunk 16]
```diff
@@ -2742,3 +2727,20 @@ fn parse_network(value: u32) -> anyhow::Result<Network> {
...
+
+fn parse_txid(env: &JNIEnv, txid_bytes: &JByteArray) -> anyhow::Result<TxId> {
+    let txid_bytes = utils::java_bytes_to_rust(env, &txid_bytes)?;
+    Ok(TxId::read(&txid_bytes[..])?)
+}
+
+fn parse_pczt(env: &JNIEnv, pczt: &JByteArray) -> anyhow::Result<Pczt> {
+    Pczt::parse(&utils::java_bytes_to_rust(env, &pczt)?)
+        .map_err(|e| anyhow!("Invalid PCZT: {:?}", e))
+}
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs]: Move all the conversion helpers together.

File: backend-lib/src/main/rust/lib.rs [hunk 17]
```diff
@@ -1050,7 +1050,7 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_writeBloc
     _: JClass<'local>,
     db_cache: JString<'local>,
     block_meta: JObjectArray<'local>,
-) -> jboolean {
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:1000]: The same argument applies to `initBlockMetaDb`: the return value is always discarded.

**Review by daira — APPROVED** [review]
utACK with non-blocking suggestions. The errors in `info_span!` strings should be addressed but it would be fine to do so in another PR. Note that, as pointed out in #1688, there are easily fixable clippy lint failures.

File: backend-lib/src/main/rust/lib.rs [hunk 18]
```diff
@@ -2686,63 +2720,19 @@ fn parse_network(value: u32) -> anyhow::Result<Network> {
...
-    account_uuid: JByteArray<'local>,
-    network_id: jint,
-) -> jobjectArray {
-    let res = catch_unwind(&mut env, |env| {
-        let _span = tracing::info_span!("RustBackend.listTransparentReceivers").entered();
-        let network = parse_network(network_id as u32)?;
-        let zcash_network = network.network_type();
-        let db_data = wallet_db(env, network, db_data)?;
-        let account = account_id_from_jni(&env, account_uuid)?;
+fn parse_secret(env: &JNIEnv, secret_bytes: &JByteArray) -> anyhow::Result<SecretVec<u8>> {
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:2723]:
```suggestion
fn parse_secret(env: &JNIEnv, secret_bytes: JByteArray) -> anyhow::Result<SecretVec<u8>> {
```
We are inconsistent (e.g. between `account_id_from_jni` and here) about whether we pass `JByteArray` or `&JByteArray`. Since `JByteArray` is implemented as an (indirect) wrapper around a pointer with only zero-size extra information, there is no need to pass a reference &mdash; but in any case be consistent.

File: backend-lib/src/main/rust/utils.rs [hunk 19]
```diff
@@ -33,14 +33,30 @@ pub fn catch_unwind<F: FnOnce(&mut JNIEnv) -> R + UnwindSafe, R>(
     })
 }
 
-pub(crate) fn java_string_to_rust(env: &mut JNIEnv, jstring: &JString) -> String {
-    env.get_string(jstring)
-        .expect("Couldn't get Java string!")
-        .into()
+pub(crate) fn java_bytes_to_rust(env: &JNIEnv, jbytes: &JByteArray) -> anyhow::Result<Vec<u8>> {
```
Comment (daira) [inline backend-lib/src/main/rust/utils.rs:36]: This could be `jbytes: JByteArray` since it is effectively already a pointer, as above.

File: backend-lib/src/main/rust/utils.rs [hunk 20]
```diff
@@ -33,14 +33,30 @@ pub fn catch_unwind<F: FnOnce(&mut JNIEnv) -> R + UnwindSafe, R>(
...
+    Ok(env.convert_byte_array(jbytes)?)
 }
 
-pub(crate) fn java_nullable_string_to_rust(env: &mut JNIEnv, jstring: &JString) -> Option<String> {
-    (!jstring.is_null()).then(|| java_string_to_rust(env, jstring))
+pub(crate) fn java_nullable_bytes_to_rust(
+    env: &JNIEnv,
+    jbytes: &JByteArray,
```
Comment (daira) [inline backend-lib/src/main/rust/utils.rs:42]: This could be `jbytes: JByteArray` since it is effectively already a pointer (see the comment on `parse_secret`).

File: backend-lib/src/main/rust/utils.rs [hunk 21]
```diff
@@ -33,14 +33,30 @@ pub fn catch_unwind<F: FnOnce(&mut JNIEnv) -> R + UnwindSafe, R>(
...
+) -> anyhow::Result<Option<Vec<u8>>> {
+    (!jbytes.is_null())
+        .then(|| java_bytes_to_rust(env, jbytes))
+        .transpose()
+}
+
+pub(crate) fn java_string_to_rust(env: &mut JNIEnv, jstring: &JString) -> anyhow::Result<String> {
```
Comment (daira) [inline backend-lib/src/main/rust/utils.rs:49]: This could be `jstring: JString` since it is effectively already a pointer (see the comment on `parse_secret`).

File: backend-lib/src/main/rust/utils.rs [hunk 22]
```diff
@@ -33,14 +33,30 @@ pub fn catch_unwind<F: FnOnce(&mut JNIEnv) -> R + UnwindSafe, R>(
...
+    Ok(env.get_string(jstring)?.into())
+}
+
+pub(crate) fn java_nullable_string_to_rust(
+    env: &mut JNIEnv,
+    jstring: &JString,
```
Comment (daira) [inline backend-lib/src/main/rust/utils.rs:55]: This could be `jstring: JString` since it is effectively already a pointer (see the comment on `parse_secret`).

**Review by nuttycom — APPROVED** [review]
utACK c78afc7d989bb74e1e375e38a62e472988495fe3

File: backend-lib/src/main/rust/lib.rs (hunk 10 above)
Comment (str4d) [reply backend-lib/src/main/rust/lib.rs:2150]: We cannot rename the JNI method, because the arguments between the extern function and the Backend trait method are identical. You'll see I use different names for several such methods, whereas when the Backend trait method has fewer arguments (e.g. due to us inserting a `db_data` path for the JNI) we use the same method name.

File: backend-lib/src/main/rust/lib.rs (hunk 12 above)
Comment (str4d) [reply backend-lib/src/main/rust/lib.rs:2522]: We cannot use `Path::new` in the helper like this because it is a reference type, and this would lead to an early drop of a temporary variable. We are instead forced to reallocate in a `PathBuf`. But that's fine.

File: backend-lib/src/main/rust/utils.rs (hunk 19 above)
Comment (str4d) [reply backend-lib/src/main/rust/utils.rs:36]: Leaving as-is because the method it wraps takes a reference, and this method doesn't do anything special on top (the type-specific helper methods do by comparison; they effectively are converting type, so we want to move there).

File: backend-lib/src/main/rust/lib.rs [hunk 23]
```diff
@@ -2720,19 +2646,76 @@ fn parse_network(value: u32) -> anyhow::Result<Network> {
...
+    type Error = anyhow::Error;
+
+    fn try_from_raw_unified(
+        data: zcash_address::unified::Address,
+    ) -> Result<Self, zcash_address::ConversionError<Self::Error>> {
+        data.try_into()
+            .map(UnifiedAddressParser)
+            .map_err(|e| anyhow!("Invalid Unified Address: {}", e).into())
+    }
+}
```
Comment (nuttycom) [inline backend-lib/src/main/rust/lib.rs:2710]: Why not just use https://github.com/zcash/librustzcash/blob/main/zcash_keys/src/address.rs#L28? 

It's really weird to me to have to go through `TryFromRawAddress` for these straightforward operations.

**Review by nuttycom — APPROVED** [review]
utACK 55299225c004ad5a5cf9bcdcaab9e7a4db865395 with suggestion

File: backend-lib/src/main/rust/lib.rs (hunk 23 above)
Comment (nuttycom) [reply backend-lib/src/main/rust/lib.rs:2710]: (I mean, why not use it directly?)

Comment (str4d) [reply backend-lib/src/main/rust/lib.rs:2710]: I _am_ using that; it's the `data.try_into()` call. The rest of the `TryFromRawAddress` machinery here is ensuring that if someone passes a string that isn't a UA (and is instead some other kind of address, or not an address at all), we get correct errors.

Comment (nuttycom) [reply backend-lib/src/main/rust/lib.rs:2710]: Ah. So, looking at the call sites of `parse_ua`, what is the reason to restrict these to unified addresses? If we parsed an arbitrary `ZcashAddress` at these call sites, we could still extract the transparent and/or Sapling receivers if present.

Comment (str4d) [reply backend-lib/src/main/rust/lib.rs:2710]: That might be worth considering, but that's outside the scope of this PR.

File: backend-lib/src/main/rust/lib.rs (hunk 10 above)
Comment (daira) [reply backend-lib/src/main/rust/lib.rs:2079]: It might be better to systematically use a different name (e.g. add an `ffi` prefix), rather than sometimes use the same name and sometimes a different one.
