### PR TITLE
Switch from ZIP 32 account indices to UUID account identifiers

### LINKED ISSUE #1633: Migrate `Account` type to the new multi-seed-compatible account identifier
Currently `Account` internally uses a ZIP 32 account index, but this will not work with either multiple seeds in the wallet (e.g. both a "daily usage" seed and a Keystone HW seed) or imported viewing keys. Once `zcash_client_sqlite` has been updated to support a new multi-seed-compatible account identifier, we need to migrate the SDK to use it.

### PR DESCRIPTION
**Pull request by str4d**
This PR is opened against `main` as a draft solely so it can be pre-reviewed. Once #1632 is complete and merged, I'll rebase this branch and then retarget it against a feature branch (so we can review and merge it before the backing Rust changes are released).

Closes #1633.

# Author

- [x] **Self-review** your own code in GitHub's web interface[^1]
- [x] Add **automated tests** as appropriate
- [ ] Update the [**manual tests**](../blob/main/docs/testing/manual_testing)[^2] as appropriate
- [ ] Check the **code coverage**[^3] report for the automated tests
- [ ] Update **documentation** as appropriate (e.g [README.md](../blob/main/README.md), [Architecture.md](../blob/main/docs/Architecture.md), etc.)
- [x] **Run the demo app** and try the changes
- [ ] Pull in the latest changes from the **main** branch and **squash** your commits before assigning a reviewer[^4]

# Reviewer

- [x] Check the code with the [Code Review Guidelines](../blob/main/docs/CODE_REVIEW_GUIDELINES.md) **checklist**
- [x] Perform an **ad hoc review**[^5]
- [ ] Review the **automated tests**
- [ ] Review the **manual tests**
- [x] Review the **documentation**, [README.md](../blob/main/README.md), [Architecture.md](/blob/main/docs/Architecture.md), etc. as appropriate
- [x] **Run the demo app** and try the changes[^6]

[^1]: _Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs._
[^2]: _While we aim for automated testing of the SDK, some aspects require manual testing. If you had to manually test 
something during development of this pull request, write those steps down._
[^3]: _While we are not looking for perfect coverage, the tool can point out potential cases that have been missed. Code coverage can be generated with: `./gradlew check` for Kotlin modules and `./gradlew connectedCheck -PIS_ANDROID_INSTRUMENTATION_TEST_COVERAGE_ENABLED=true` for Android modules._
[^4]: _Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit._
[^5]: _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
[^6]: _While the CI server runs the demo app to look for build failures or crashes, humans running the demo app are 
more likely to notice unexpected log messages, UI inconsistencies, or bad output data. Perform this step last, after verifying the code changes are safe to run locally._

### CODE REVIEW

**Comment by str4d** [comment]
[Force-pushed](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/compare/de385b259d4ef94b630e00023fa7eb927d90863f..192c5e1219c0f78702c3e83597f266b45f69d525) to rebase on `main` afer #1641 was merged.

**Review by HonzaR — COMMENTED** [review]
The `encode_usk` function in `lib.rs` still works upon ZIP32 account index, while it needs to switch to the new `account_uuid` logic to align with the updated `JniUnifiedSpendingKey` class on the Kotlin side. @str4d can you please make this change as part of this PR? My current branch `1632-remove-default-account` is built on these changes.

File: backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniAccountBalance.kt [hunk 1]
```diff
@@ -25,7 +25,7 @@ import androidx.annotation.Keep
 @Keep
 @Suppress("LongParameterList")
 class JniAccountBalance(
-    val account: Int,
+    val account: ByteArray,
```
Comment (daira) [inline backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniAccountBalance.kt:28]:
```suggestion
    val accountUuid: ByteArray,
```

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt [hunk 2]
```diff
@@ -1,16 +1,15 @@
...
 import cash.z.ecc.android.sdk.model.UnifiedFullViewingKey
 import cash.z.ecc.android.sdk.model.UnifiedSpendingKey
 import cash.z.ecc.android.sdk.model.ZcashNetwork
 
 fun Derivation.deriveUnifiedAddress(
     seed: ByteArray,
     network: ZcashNetwork,
-    account: Account
-): String = deriveUnifiedAddress(seed, network.id, account.value)
+    accountIndex: Int
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt:11]: This is different to Swift, where `Zip32AccountIndex` which wraps a `UInt32` is used.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeDerivationToolImpl.kt [hunk 3]
```diff
@@ -21,14 +20,14 @@ internal class TypesafeDerivationToolImpl(private val derivation: Derivation) :
     override suspend fun deriveUnifiedSpendingKey(
         seed: ByteArray,
         network: ZcashNetwork,
-        account: Account
-    ): UnifiedSpendingKey = derivation.deriveUnifiedSpendingKey(seed, network, account)
+        accountIndex: Int
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeDerivationToolImpl.kt:23]: Again, in Swift this uses the `Zip32AccountIndex` wrapper.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt [hunk 4]
```diff
@@ -1,16 +1,44 @@
...
+ * What this means is that account identifiers are not stable across "wallet recreation
+ * events". Examples of these include:
+ * - Restoring a wallet from a backed-up seed.
+ * - Importing the same viewing key into two different wallet instances.
  *
- * @param value A 0-based account index.  Must be >= 0.
+ * @param accountUuid The account identifier. Must be length 16.
  */
-data class Account(val value: Int) {
+data class Account(val accountUuid: ByteArray) {
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:25]: Why not call this `AccountUuid` and use it as the type passed to identify an account in other APIs (rather than `ByteArray`)? That would eliminate the need to explicitly require it to be 16 bytes in most places.

**Comment by HonzaR** [comment]
We need to ensure that [this](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1645#discussion_r1869826778) is fulfilled as part of this PR.

File: backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt [hunk 5]
```diff
@@ -98,13 +98,35 @@ class RustBackend private constructor(
     ): JniUnifiedSpendingKey {
         return withContext(SdkDispatchers.DATABASE_IO) {
             createAccount(
+                dbDataPath = dataDbFile.absolutePath,
```
Comment (nuttycom) [inline backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt:101]: I reordered the parameters here because the database file and the network id are really environment parameters, whereas the account name and key source etc. are the arguments to the logical function that's being executed.

File: backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniAccountBalance.kt (hunk 1 above)
Comment (HonzaR) [reply backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniAccountBalance.kt:28]: Resolved. Thanks for pointing this out.

File: backend-lib/src/main/rust/lib.rs [hunk 6]
```diff
@@ -288,22 +288,22 @@ fn encode_account<'a, P: Parameters>(
...
     env.new_object(
         JNI_ACCOUNT,
-        "([BLjava/lang/String;Ljava/lang/String;Ljava/lang/String;[BI)V",
+        "(Ljava/lang/String;[BJLjava/lang/String;[BLjava/lang/String;)V",
         &[
-            (&env.byte_array_from_slice(account.id().expose_uuid().as_bytes())?).into(),
-            (&ufvk).into(),
             (&account_name).into(),
+            (&env.byte_array_from_slice(account.id().expose_uuid().as_bytes())?).into(),
+            hd_account_index,
```
Comment (nuttycom) [inline backend-lib/src/main/rust/lib.rs:303]: Nit: the hd_account_index and seed fingerprint go together, as they're the two necessary bits of HD derivation information.

File: demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Constants.kt [hunk 7]
```diff
@@ -10,6 +10,8 @@ val ANDROID_STATE_FLOW_TIMEOUT = 5.seconds
  */
 const val MINIMAL_WEIGHT = 0.0001f
 
-// TODO [#1644]: Refactor Account ZIP32 index across SDK
-// TODO [#1644]: https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1644
+/**
+ * Until we support full multi-account feature in Demo app we use this constant as a single source of truth for
+ * account selection
+ */
```
Comment (nuttycom) [inline demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Constants.kt:16]: This should no longer be necessary? Is it even still possible to query by ZIP 32 account index?

Comment (nuttycom) [reply demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Constants.kt:16]: Never mind, saw that this is the demo app.

File: demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt [hunk 8]
```diff
@@ -104,11 +105,13 @@ class WalletViewModel(application: Application) : AndroidViewModel(application)
                     withContext(Dispatchers.IO) {
                         Mnemonics.MnemonicCode(it.seedPhrase.joinToString()).toSeed()
                     }
+                val accountIndex = getCurrentAccount().hdAccountIndex?.toInt()
+                    ?: error("The account must be set at this point")
```
Comment (nuttycom) [inline demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt:109]: Ideally the spending key would only be derived right before it is used for spending; it would not be constructed ahead of time.

Comment (nuttycom) [reply demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt:109]: In support of that, instead of this being an error, I would have the whole spending key be a nullable value and set to null if the hd account index is not available. But maybe that will change with multi-account support instead?

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt [hunk 9]
```diff
@@ -20,8 +19,15 @@ fun Derivation.deriveUnifiedAddress(
...
     seed: ByteArray,
     network: ZcashNetwork,
-    account: Account
-): UnifiedSpendingKey = UnifiedSpendingKey(deriveUnifiedSpendingKey(seed, network.id, account.value))
+    accountIndex: Int
+): UnifiedSpendingKey =
+    UnifiedSpendingKey(
+        JniUnifiedSpendingKey(
+            // fixme
+            accountUuid = byteArrayOf(),
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt:27]: This needs to be finished.

**Review by daira — COMMENTED** [review]
Unfinished but looks good so far. Please add a `Zip32AccountIndex` class to replace `Int` for ZIP 32 account indices.

File: backend-lib/src/main/rust/lib.rs [hunk 10]
```diff
@@ -438,17 +421,128 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createAcc
...
+/// Tells the wallet to track an account using a unified full viewing key.
+///
+/// Returns details about the imported account, including the unique account identifier for
+/// the newly-created wallet database entry. Unlike the other account creation APIs
+/// ([`Self::create_account`] and [`Self::import_account_hd`]), no spending key is returned
+/// because the wallet has no information about how the UFVK was derived.
+///
+/// Certain optimizations are possible for accounts which will never be used to spend funds. If
+/// `spending_key_available` is `false`, the wallet may choose to optimize for this case, in
+/// which case any attempt to spend funds from the account will result in an error.
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:450]: It's unclear whether this should apply to the hardware wallet case. Does `spending_key_available` mean:
1. That the spending key is unavailable to the SDK (but the SDK might still have to track other things necessary to make proofs, for example), or
2. That the account will never be spent from, and so no spend-related information needs to be tracked?

From the description in this paragraph I would assume 2, but from the name `spending_key_available` I would assume 1.

**Comment by nuttycom** [comment]
This is really used to answer the “should the wallet track spending
metadata” question.

File: backend-lib/src/main/rust/lib.rs [hunk 11]
```diff
@@ -438,17 +421,128 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createAcc
...
+            .zip(hd_account_index)
+            .map(|(seed_fp, idx)| Zip32Derivation::new(seed_fp, idx));
+
+        let purpose = match purpose {
+            0 => Ok(AccountPurpose::Spending { derivation }),
+            1 => Ok(AccountPurpose::ViewOnly),
+            _ => Err(anyhow!(
+                "Account purpose must be either 0 (Spending) or 1 (ViewOnly)"
+            )),
+        }?;
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:533]: `seed_fingerprint`, `hd_account_index`, and `derivation` are only used if `purpose` is 0. Is the following suggestion equivalent, or are we relying on deriving those values for error checking?
```suggestion
        let purpose = match purpose {
            0 => {
                let seed_fingerprint =
                    <[u8; 32]>::try_from(&env.convert_byte_array(seed_fingerprint_bytes)?[..])
                    .ok()
                    .map(SeedFingerprint::from_bytes);
                let hd_account_index = zip32::AccountId::try_from(hd_account_index_raw).ok();

                let derivation = seed_fingerprint
                    .zip(hd_account_index)
                    .map(|(seed_fp, idx)| Zip32Derivation::new(seed_fp, idx));

                Ok(AccountPurpose::Spending { derivation })
            },
            1 => Ok(AccountPurpose::ViewOnly),
            _ => Err(anyhow!(
                "Account purpose must be either 0 (Spending) or 1 (ViewOnly)"
            )),
        }?;
```

File: backend-lib/src/main/rust/lib.rs [hunk 12]
```diff
@@ -438,17 +421,128 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createAcc
...
+///   birthday height.
+/// - `recover_until`: An optional height at which the wallet should exit "recovery mode". In
+///    order to avoid confusing shifts in wallet balance and spendability that may temporarily be
+///    visible to a user during the process of recovering from seed, wallets may optionally set a
+///    "recover until" height. The wallet is considered to be in "recovery mode" until there
+///    exist no unscanned ranges between the wallet's birthday height and the provided
+///   `recover_until` height, exclusive.
+/// - `key_source`: A string identifier or other metadata describing the source of the seed.
+///   This is treated as opaque metadata by the wallet backend; it is provided for use by
+///   applications which need to track additional identifying information for an account.
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:469]:
```suggestion
/// - `key_source`: A string identifier or other metadata describing the source of the seed.
///   This is treated as opaque metadata by the wallet backend; it is provided for use by
///   applications which need to track additional identifying information for an account.
/// - `ufvk_str`: The UFVK used to detect transactions involving the account.
/// - `treestate`: The tree state corresponding to the last block prior to the wallet's
///   birthday height.
/// - `recover_until`: An optional height at which the wallet should exit "recovery mode". In
///    order to avoid confusing shifts in wallet balance and spendability that may temporarily be
///    visible to a user during the process of recovering from seed, wallets may optionally set a
///    "recover until" height. The wallet is considered to be in "recovery mode" until there
///    exist no unscanned ranges between the wallet's birthday height and the provided
///   `recover_until` height, exclusive.
/// - `purpose`: 0 (Spending) if data required for spending should be tracked by the wallet,
///   or 1 (ViewOnly) if the account will never be used to spend funds.
/// - `seed_fingerprint_bytes`: the [seed fingerprint]. Only used if `purpose` is 0 (Spending).
/// - `hd_account_index_raw`: the ZIP 32 account index. Only used if `purpose` is 0 (Spending).
///
/// [seed fingerprint]: https://zips.z.cash/zip-0032#seed-fingerprints
```

**Review by daira — COMMENTED** [review]
Reviewed with comments.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt [hunk 13]
```diff
@@ -73,9 +72,9 @@ internal class TxOutputsView(private val sqliteDatabase: SupportSQLiteDatabase)
                 if (!it.isNull(toAccountIndex)) {
                     // TODO [#1644]: Refactor Account ZIP32 index across SDK
                     // TODO [#1644]: https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1644
-                    TransactionRecipient.Account(0)
+                    TransactionRecipient.RecipientAccount(it.getInt(toAccountIndex))
```
[the remark this answers is not in the document]
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/db/derived/TxOutputsView.kt]: Done

File: demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Constants.kt (hunk 7 above)
Comment (HonzaR) [reply demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/Constants.kt:16]: This constant is part of Demo app only, and we use it only for account 0 selection across the Demo app's use cases. whereas Zashi works with `getAccounts`.

File: backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt (hunk 5 above)
Comment (HonzaR) [reply backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt:101]: Oh, I see now. Later, I sorted the parameters alphabetically, which is what we do across the SDK. Do you want me to change it as you described?

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt (hunk 2 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt:11]: We could add this change. Let's use the same wrapper, but with the only difference in the inner parameter type as `Long`, and check the value for its scope as we do, e.g., in the case of `BlockHeight` [parameters](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/blob/6f9ab065df6a5c277ad6174759c02c3ca2fd0c01/backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/model/JniRewindResult.kt#L19). We can't use unsigned numbers across SDK as they are not supported by Java, which we need for many APIs used in protobug files.

File: demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt (hunk 8 above)
Comment (HonzaR) [reply demo-app/src/main/java/cash/z/ecc/android/sdk/demoapp/ui/screen/home/viewmodel/WalletViewModel.kt]: The `spendingKey` variable is a Kotlin StateFlow with a default value of null, which changes once we start observing the stream. So yes, we could leave null instead of throwing the error. The change pushed.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 4 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt]: Yes, we can do this optimization.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt [hunk 14]
```diff
@@ -20,8 +20,16 @@ fun Derivation.deriveUnifiedAddress(
...
     network: ZcashNetwork,
-    account: Account
-): UnifiedSpendingKey = UnifiedSpendingKey(deriveUnifiedSpendingKey(seed, network.id, account.value))
+    accountIndex: Int
+): UnifiedSpendingKey =
+    UnifiedSpendingKey(
+        JniUnifiedSpendingKey(
+            // FIXME: How to construct JniUnifiedSpendingKey without accountUuid?
+            // FIXME: The tests fixture currently used to pass tests
+            accountUuid = AccountFixture.new().accountUuid,
```
Comment (HonzaR) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt:29]: This is a bit tricky now. As the `deriveUnifiedSpendingKey` started to return `ByteArray` instead of the previously used `JniUnifiedSpendingKey`. Now we can't easily construct `UnifiedSpendingKey` just from `accountIndex`. Any ideas please? @str4d @nuttycom

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt [hunk 15]
```diff
@@ -1,12 +1,113 @@
...
+ * @param keySource A string identifier or other metadata describing the source of the seed
+ * @param seedFingerprint The seed fingerprint. Must be length 16.
+ * @param hdAccountIndex ZIP 32 account index
  */
-data class Account(val value: Int) {
+data class Account internal constructor(
+    val accountUuid: ByteArray,
+    val ufvk: String?,
+    val accountName: String?,
+    val keySource: String?,
```
Comment (Milan-Cerovsky) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: keysource we use should be "Keystone" or "Zashi", right?

Comment (Milan-Cerovsky) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: account name probably too 🤔

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt [hunk 16]
```diff
@@ -1,12 +1,113 @@
...
+    override fun toString(): String {
+        return "Account(accountUuid=${accountUuid.contentToString()}," +
+            " ufvk length=${ufvk?.length}," +
+            " accountName=$accountName," +
+            " keySource=$keySource," +
+            " seedFingerprint size=${seedFingerprint?.size}," +
+            " hdAccountIndex=$hdAccountIndex)"
+    }
+
+    override fun equals(other: Any?): Boolean {
```
Comment (Milan-Cerovsky) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:83]: we probably do not need to override equals and hasCode here

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt [hunk 17]
```diff
@@ -1,12 +1,113 @@
...
+            "Account UUID must be 16 bytes"
+        }
+        seedFingerprint?.let {
+            require(seedFingerprint.size == JNI_ACCOUNT_SEED_FP_BYTES_SIZE) {
+                "Seed fingerprint must be 32 bytes"
+            }
+        }
+    }
+
+    companion object {
```
Comment (Milan-Cerovsky) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:51]: put companion object to the bottom of the class and u can even name it 'companion object Factory' for it to be evident what it is

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountCreateSetup.kt [hunk 18]
```diff
@@ -0,0 +1,35 @@
...
+ * @param keySource A string identifier or other metadata describing the source of the seed
+ * @param seed the wallet's seed phrase. This is required the first time a new wallet is set up. For
+ * subsequent calls, seed is only needed if [InitializerException.SeedRequired] is thrown.
+ */
+data class AccountCreateSetup(
+    val accountName: String,
+    val keySource: String?,
+    val seed: ByteArray,
+) {
+    override fun equals(other: Any?): Boolean {
```
Comment (Milan-Cerovsky) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountCreateSetup.kt:16]: equals and hashCode are generated by data class here too so we probably do not need to override it

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt [hunk 19]
```diff
@@ -132,14 +135,28 @@ interface Synchronizer {
...
+     *
+     * @throws [InitializeException.ImportAccountException] in case of the operation failure
      */
-    suspend fun getFastestServers(
-        context: Context,
-        servers: List<LightWalletEndpoint>
-    ): Flow<FastestServersResult>
+    suspend fun importAccountByUfvk(
+        purpose: AccountPurpose,
+        recoverUntil: Long?,
```
Comment (Milan-Cerovsky) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt:156]: where do we get recoverUntil and treeState from ?

**Review by Milan-Cerovsky — CHANGES_REQUESTED** [review]

**Comment by Milan-Cerovsky** [comment]
@HonzaR please merge feature branch into this one

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 15 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: As we discussed with @LukasKorba, I vote for using all caps `KEYSTONE` and `ZASHI` in case the `keySource`. The `accountName` parameter could not be tied by any rules.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 16 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:83]: The `equals` and `hashCode` are required due to the `ByteArray` parameters in this class.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountCreateSetup.kt (hunk 18 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountCreateSetup.kt:16]: The `equals` and `hashCode` are required due to the `ByteArray` parameter in this class.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt (hunk 19 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/Synchronizer.kt:156]: It's the same as in the case of the `createAccount` API. Check its usage, please.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 15 above)
Comment (LukasKorba) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: I used `Keystone` and `Zashi` atm. If we want to set some rules here, we can go either with lowercased or uppcased approach. In iOS world, uppcased is very rare so I would rather use `keystone` and `zashi`.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 17 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:51]: We can do this later after a discussion in a follow-up to make such a change across the SDK. We use this naming and ordering, if you agree?

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 15 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: Okay, let's use the lowercase version, then.  @Milan-Cerovsky do you agree?

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt (hunk 14 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt:29]: I see now. I just got details about this from @LukasKorba that we should remove all account-related information from spending and viewing key objects. Then, we can update this easily.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 15 above)
Comment (Milan-Cerovsky) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: yes lets go with it

Comment (LukasKorba) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:36]: FYI, I updated the code to follow the lowercase rule

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt (hunk 4 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt]: Done

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeDerivationToolImpl.kt (hunk 3 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeDerivationToolImpl.kt]: Done

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt (hunk 2 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/DerivationToolExt.kt]: Done

**Review by HonzaR — COMMENTED** [review]
Self-reviewed. I left a few comments. Pushing changes to address few more.

File: CHANGELOG.md [hunk 20]
```diff
@@ -7,18 +7,28 @@ and this library adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
 ## [Unreleased]
 
 ### Added
-- `Synchronizer.getAccounts()`
-- `Synchronizer.walletBalances: StateFlow<Map<Account, AccountBalance>?>` that is replacement for the removed 
+- `Synchronizer.importAccountByUfvk()` has been added
+- `Synchronizer.getAccounts()` returning all the created or imported accounts. See the documentation in `Account`.
+- `Synchronizer.walletBalances: StateFlow<Map<AccountUuid, AccountBalance>?>` that is replacement for the removed 
   `orchardBalances`, `saplingBalances`, and `transparentBalance`
+- `getTransactions(accountUuid: AccountUuid)` to get transactions belonging to the given account
```
Comment (daira) [inline CHANGELOG.md:14]:
```suggestion
- `getTransactions(accountUuid: AccountUuid)` to get transactions belonging to the given account
- `model.Zip32AccountIndex`
```
Please check for other additions.

Comment (HonzaR) [reply CHANGELOG.md:14]: Changelog updated.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt [hunk 21]
```diff
@@ -663,6 +692,48 @@ class SdkSynchronizer private constructor(
...
+                chainTip ?: network.saplingActivationHeight
+            )
+        val treeState: TreeState = loadedCheckpoint.treeState()
+
+        return runCatching {
+            backend.importAccountUfvk(
+                purpose = purpose,
+                recoverUntil = chainTip?.value,
+                setup = setup,
+                treeState = treeState.encoded,
```
Comment (str4d) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/SdkSynchronizer.kt:726]:
```suggestion
                recoverUntil = chainTip,
                setup = setup,
                treeState = treeState,
```

**Review by str4d — COMMENTED** [review]
Reviewed 0b603e2927f111d65af40632c541f3e2338ebf5b. I did not review the changes to the tests or the demo app.

Changes requested (I can't mark as such because I opened the PR).

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountPurpose.kt [hunk 22]
```diff
@@ -0,0 +1,25 @@
...
+sealed class AccountPurpose {
+    /**
+     * Constant value that uniquely identifies this enum across FFI
+     */
+    abstract val value: Int
+
+    /**
+     * For spending accounts, the wallet will track information needed to spend received notes
+     */
+    data object Spending : AccountPurpose() {
```
[the remark this answers is not in the document]
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountPurpose.kt:15]: Yes, on it.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountCreateSetup.kt [hunk 23]
```diff
@@ -0,0 +1,35 @@
...
+ *
+ * @param accountName A human-readable name for the account
+ * @param keySource A string identifier or other metadata describing the source of the seed
+ * @param seed the wallet's seed phrase. This is required the first time a new wallet is set up. For
+ * subsequent calls, seed is only needed if [InitializerException.SeedRequired] is thrown.
+ */
+data class AccountCreateSetup(
+    val accountName: String,
+    val keySource: String?,
+    val seed: ByteArray,
```
[the remark this answers is not in the document]
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountCreateSetup.kt:17]: Yes, I'm adding this change, too. We could make such a change to the other APIs, too, to eliminate the need to override the `equals` and `hashCode`, though. That is the primary purpose of the class, I believe. We could also rename it a bit, so it makes a bit more sense. Going further we could then use it in the public APIs that still work with `ByteArray`.

**Review by str4d — COMMENTED** [review]
utACK 7a064ece9cda0064bee9d7b1da1ffd44d37acaf9. Any further changes can be made in subsequent PRs to the feature branch.

File: backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt (hunk 5 above)
Comment (nuttycom) [reply backend-lib/src/main/java/cash/z/ecc/android/sdk/internal/jni/RustBackend.kt:101]: No, consistency is better (though alphabetical parameter lists seems like not a great convention to me.)

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt [hunk 24]
```diff
@@ -25,6 +25,7 @@ internal interface TransactionEncoder {
      */
     suspend fun createTransaction(
         usk: UnifiedSpendingKey,
+        account: Account,
```
Comment (nuttycom) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt:28]: We should probably look up the account by deriving the UFVK from the USK and then using that to determine the account ID here.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt [hunk 25]
```diff
@@ -47,25 +47,39 @@ internal class TransactionEncoderImpl(
...
         amount: Zatoshi,
         recipient: TransactionRecipient,
         memo: ByteArray?
     ): EncodedTransaction {
-        require(recipient is TransactionRecipient.Address)
+        require(recipient is TransactionRecipient.RecipientAddress)
 
-        val transactionId = createSpend(usk, amount, recipient.addressValue, memo)
+        val transactionId =
+            createSpend(
```
Comment (nuttycom) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoderImpl.kt:58]: It is actually `createSpend` that needs to change, and then that can propagate up.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountUsk.kt [hunk 26]
```diff
@@ -0,0 +1,74 @@
...
+    val accountUuid: AccountUuid,
+    /**
+     * The binary encoding of the [ZIP 316](https://zips.z.cash/zip-0316) Unified Spending
+     * Key for [accountUuid].
+     *
+     * This encoding **MUST NOT** be exposed to users. It is an internal encoding that is
+     * inherently unstable, and only intended to be passed between the SDK and the storage
+     * backend. Wallets **MUST NOT** allow this encoding to be exported or imported.
+     */
+    private val bytes: FirstClassByteArray
```
Comment (nuttycom) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountUsk.kt:28]: Why is this not `UnifiedSpendingKey`?

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt (hunk 24 above)
Comment (nuttycom) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt:28]: To clarify, `account` should not be an additional parameter, because we have enough information to discover it inside of `createSpend`.

**Review by nuttycom — COMMENTED** [review]
post-hoc ACK, but before release we should remove the `Account` parameter from `createSpend` etc. and look those up based on the USK.

File: backend-lib/src/main/rust/lib.rs [hunk 27]
```diff
@@ -438,17 +421,132 @@ pub extern "C" fn Java_cash_z_ecc_android_sdk_internal_jni_RustBackend_createAcc
...
+/// - `recover_until`: An optional height at which the wallet should exit "recovery mode". In
+///    order to avoid confusing shifts in wallet balance and spendability that may temporarily be
+///    visible to a user during the process of recovering from seed, wallets may optionally set a
+///    "recover until" height. The wallet is considered to be in "recovery mode" until there
+///    exist no unscanned ranges between the wallet's birthday height and the provided
+///   `recover_until` height, exclusive.
+/// - `purpose`: 0 (Spending) if data required for spending should be tracked by the wallet,
+///   or 1 (ViewOnly) if the account will never be used to spend funds.
+/// - `seed_fingerprint_bytes`: the [seed fingerprint]. Only used if `purpose` is 0 (Spending).
+/// - `hd_account_index_raw`: the ZIP 32 account index. Only used if `purpose` is 0 (Spending).
```
Comment (daira) [inline backend-lib/src/main/rust/lib.rs:471]: The suggestions to add "Only used if `purpose` is 0 (Spending)." depended on the suggestion [below](https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/pull/1640/files#r1874197278) to only convert/check these parameters in that case. By taking the comment suggestion but not the code suggestion, this is now incorrectly documented, because `seed_fingerprint_bytes` has to point to a 32-byte array and `hd_account_index_raw` has to be in the range of a valid ZIP 32 account index, *regardless* of `purpose`.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt [hunk 28]
```diff
@@ -27,29 +30,67 @@ internal class TypesafeBackendImpl(private val backend: Backend) : TypesafeBacke
...
+                    AccountPurpose.ViewOnly ->
+                        backend.importAccountUfvk(
+                            accountName = setup.accountName,
+                            keySource = setup.keySource,
+                            purpose = setup.purpose.value,
+                            recoverUntil = recoverUntil?.value,
+                            treeState = treeState.encoded,
+                            ufvk = setup.ufvk.encoding,
+                            seedFingerprint = null,
+                            zip32AccountIndex = null,
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt:81]: Bug: these are not valid values for `seedFingerprint` and `zip32AccountIndex`.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt (hunk 24 above)
Comment (daira) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/transaction/TransactionEncoder.kt:28]: Filed #1652.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt [hunk 29]
```diff
@@ -1,12 +1,117 @@
...
  *
- * @param value A 0-based account index.  Must be >= 0.
+ * @param accountUuid The account identifier.
+ * @param ufvk The account's Unified Full Viewing Key, if any.
+ * @param accountName A human-readable name for the account. This is visible to the wallet user, and
+ *        the wallet app may have obtained it from them.
+ * @param keySource A string identifier or other metadata describing the location of the spending
+ *        key corresponding to the account's UFVK. This is set internally by the wallet app based on
+ *        its private enumeration of spending methods it supports.
+ * @param seedFingerprint The seed fingerprint. Must be length 16.
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:31]: This does not match "Seed fingerprint must be 32 bytes" (which indeed is the value of `JNI_ACCOUNT_SEED_FP_BYTES_SIZE`).

Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Account.kt:31]: Good catch. Thank you!

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt (hunk 28 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/internal/TypesafeBackendImpl.kt:81]: Discussion and findings moved to https://github.com/Electric-Coin-Company/zcash-android-wallet-sdk/issues/1651

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountUsk.kt (hunk 26 above)
Comment (HonzaR) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountUsk.kt:28]: Yes, we could do that. Good point.

Comment (daira) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/AccountUsk.kt:28]: Filed as #1654.

File: sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Zip32AccountIndex.kt [hunk 30]
```diff
@@ -0,0 +1,22 @@
...
+ *
+ * @param index The account ZIP 32 account identifier
+ */
+data class Zip32AccountIndex internal constructor(
+    val index: Long
+) {
+    init {
+        require(index.isInUIntRange()) {
+            "Account index $index is outside of allowed UInt range"
+        }
```
Comment (daira) [inline sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Zip32AccountIndex.kt:16]: The valid range of a ZIP 32 account index is $[0, 2^{31})$, not $[0, 2^{32})$.

Comment (daira) [reply sdk-lib/src/main/java/cash/z/ecc/android/sdk/model/Zip32AccountIndex.kt:16]: Filed #1655.

File: sdk-lib/src/test/java/cash/z/ecc/android/sdk/model/AccountTest.kt [hunk 31]
```diff
@@ -1,13 +1,15 @@
...
 import org.junit.Test
+import java.util.UUID
 import kotlin.test.assertFailsWith
 
 class AccountTest {
     @Test
     fun out_of_bounds() {
         assertFailsWith(IllegalArgumentException::class) {
-            Account(-1)
+            AccountFixture.new(accountUuid = UUID.fromString("random"))
```
Comment (daira) [inline sdk-lib/src/test/java/cash/z/ecc/android/sdk/model/AccountTest.kt:12]: Why is this invalid? I'm surprised it passes.

**Review by daira — COMMENTED** [review]
Post-hoc ACK with comments. Follow-up tickets: #1651, #1652, #1654, #1655.

File: backend-lib/src/main/rust/lib.rs (hunk 11 above)
Comment (nuttycom) [reply backend-lib/src/main/rust/lib.rs:537]: Fixed in #1656
